title: Nahil Hind # your name (or website title) here
logo: "/images/hindn.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Récemment diplômée en ingénierie informatique et réseaux, option MIAGE, je suis une ingénieure junior passionnée par les nouvelles technologies et les défis qu'elles apportent. Avec une grande capacité d'adaptation et une forte motivation, je suis déterminée à contribuer activement à des projets innovants en apportant des solutions créatives et efficaces. Mon objectif est de collaborer au sein d'une équipe dynamique pour développer des applications et systèmes répondant aux besoins d'un monde en constante évolution.<br>
  Second description 
  <br>### Compétences  

Passionnée par l'innovation, je maîtrise des technologies variées comme **Java, Python, C#**, ainsi que des frameworks modernes tels que **Spring Boot, Laravel, Angular, et React**. Je suis également experte en bases de données (**MySQL, SQL Server**) et en **business intelligence** avec **Power BI, SSIS, et SSAS**. Mon expérience inclut aussi le développement mobile avec **Flutter et Firebase**, ainsi que l'administration de systèmes (**Unix, Windows Server**). Je suis prête à relever des défis techniques dans un environnement collaboratif.  <br>
  <a href="https://www.linkedin.com/in/hind-nahil">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
