#title: Nahil Hind # your name (or website title) here
#logo: "/images/nahil.jpeg?raw=true" # your photo (or logo) here
#description: > # your text below (remove <br> elements if you don't need line breaks)
  #First description 
  #<br> <br>
 # Second description 
 # <br> <br>
 # <a href="https://www.linkedin.com/in/hind-nahil">View My LinkedIn Profile</a> 
  
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
title: Nahil Hind
logo: "/images/nahil.jpeg?raw=true"
description: >
  Récemment diplômée en ingénierie informatique et réseaux, option MIAGE, je suis une ingénieure junior passionnée par les nouvelles technologies. Je maîtrise des langages comme Java, Python, C#, ainsi que des frameworks tels que Spring Boot, Laravel, Angular et React. J'ai également des compétences en bases de données (MySQL, SQL Server), business intelligence (Power BI, SSIS, SSAS), et développement mobile (Flutter, Firebase). Motivé et adaptable, je souhaite contribuer à des projets innovants en collaborant au sein d'équipes dynamiques.
  <br> <br>
  
  <a href="https://www.linkedin.com/in/hind-nahil">Voir mon profil LinkedIn</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0

